// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(KkcsDbContext))]
    [Migration("20261003065149_TambahCatatanNeraca")]
    partial class TambahCatatanNeraca
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AkunAkuntansi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DibuatPada")
                        .HasColumnType("datetime2");

                    b.Property<string>("Kode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("SaldoNormal")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("Sistem")
                        .HasColumnType("bit");

                    b.Property<string>("Tipe")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Kode")
                        .IsUnique();

                    b.ToTable("AkunAkuntansi");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Aktif = true,
                            DibuatPada = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Kode = "1-1000",
                            Nama = "Kas & Bank",
                            SaldoNormal = "Debit",
                            Sistem = true,
                            Tipe = "Aset"
                        },
                        new
                        {
                            Id = 2,
                            Aktif = true,
                            DibuatPada = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Kode = "1-1200",
                            Nama = "Piutang Pinjaman Anggota",
                            SaldoNormal = "Debit",
                            Sistem = true,
                            Tipe = "Aset"
                        },
                        new
                        {
                            Id = 3,
                            Aktif = true,
                            DibuatPada = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Kode = "1-1300",
                            Nama = "Piutang Kredit Produk (Potong Gaji)",
                            SaldoNormal = "Debit",
                            Sistem = true,
                            Tipe = "Aset"
                        },
                        new
                        {
                            Id = 4,
                            Aktif = true,
                            DibuatPada = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Kode = "1-1400",
                            Nama = "Persediaan Barang",
                            SaldoNormal = "Debit",
                            Sistem = false,
                            Tipe = "Aset"
                        },
                        new
                        {
                            Id = 5,
                            Aktif = true,
                            DibuatPada = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Kode = "2-2200",
                            Nama = "Simpanan Sukarela Anggota",
                            SaldoNormal = "Kredit",
                            Sistem = true,
                            Tipe = "Liabilitas"
                        },
                        new
                        {
                            Id = 6,
                            Aktif = true,
                            DibuatPada = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Kode = "2-2300",
                            Nama = "Simpanan Berjangka Anggota",
                            SaldoNormal = "Kredit",
                            Sistem = true,
                            Tipe = "Liabilitas"
                        },
                        new
                        {
                            Id = 7,
                            Aktif = true,
                            DibuatPada = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Kode = "2-2400",
                            Nama = "Utang PPh Ps 4(2) — Bunga Simpanan",
                            SaldoNormal = "Kredit",
                            Sistem = true,
                            Tipe = "Liabilitas"
                        },
                        new
                        {
                            Id = 8,
                            Aktif = true,
                            DibuatPada = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Kode = "2-2500",
                            Nama = "Utang SHU ke Anggota",
                            SaldoNormal = "Kredit",
                            Sistem = true,
                            Tipe = "Liabilitas"
                        },
                        new
                        {
                            Id = 9,
                            Aktif = true,
                            DibuatPada = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Kode = "3-3100",
                            Nama = "Simpanan Pokok (Modal Anggota)",
                            SaldoNormal = "Kredit",
                            Sistem = true,
                            Tipe = "Ekuitas"
                        },
                        new
                        {
                            Id = 10,
                            Aktif = true,
                            DibuatPada = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Kode = "3-3200",
                            Nama = "Simpanan Wajib (Modal Anggota)",
                            SaldoNormal = "Kredit",
                            Sistem = true,
                            Tipe = "Ekuitas"
                        },
                        new
                        {
                            Id = 11,
                            Aktif = true,
                            DibuatPada = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Kode = "3-3900",
                            Nama = "SHU Ditahan / Cadangan",
                            SaldoNormal = "Kredit",
                            Sistem = true,
                            Tipe = "Ekuitas"
                        },
                        new
                        {
                            Id = 12,
                            Aktif = true,
                            DibuatPada = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Kode = "4-4100",
                            Nama = "Pendapatan Jasa Pinjaman",
                            SaldoNormal = "Kredit",
                            Sistem = true,
                            Tipe = "Pendapatan"
                        },
                        new
                        {
                            Id = 13,
                            Aktif = true,
                            DibuatPada = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Kode = "4-4200",
                            Nama = "Pendapatan Penjualan & Sewa Produk",
                            SaldoNormal = "Kredit",
                            Sistem = true,
                            Tipe = "Pendapatan"
                        },
                        new
                        {
                            Id = 14,
                            Aktif = true,
                            DibuatPada = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Kode = "4-4300",
                            Nama = "Pendapatan Lain-lain",
                            SaldoNormal = "Kredit",
                            Sistem = false,
                            Tipe = "Pendapatan"
                        },
                        new
                        {
                            Id = 15,
                            Aktif = true,
                            DibuatPada = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Kode = "5-5100",
                            Nama = "Beban Bunga Simpanan Sukarela",
                            SaldoNormal = "Debit",
                            Sistem = true,
                            Tipe = "Beban"
                        },
                        new
                        {
                            Id = 16,
                            Aktif = true,
                            DibuatPada = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Kode = "5-5200",
                            Nama = "Beban Bunga Simpanan Berjangka",
                            SaldoNormal = "Debit",
                            Sistem = true,
                            Tipe = "Beban"
                        },
                        new
                        {
                            Id = 17,
                            Aktif = true,
                            DibuatPada = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Kode = "5-5300",
                            Nama = "Beban Pokok Penjualan",
                            SaldoNormal = "Debit",
                            Sistem = false,
                            Tipe = "Beban"
                        },
                        new
                        {
                            Id = 18,
                            Aktif = true,
                            DibuatPada = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Kode = "5-5900",
                            Nama = "Beban Operasional Lain (Gaji, Sewa, dll)",
                            SaldoNormal = "Debit",
                            Sistem = false,
                            Tipe = "Beban"
                        },
                        new
                        {
                            Id = 19,
                            Aktif = true,
                            DibuatPada = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Kode = "2-2600",
                            Nama = "Utang Jasa Pengurus, Pengawas & Admin (SHU)",
                            SaldoNormal = "Kredit",
                            Sistem = true,
                            Tipe = "Liabilitas"
                        },
                        new
                        {
                            Id = 20,
                            Aktif = true,
                            DibuatPada = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Kode = "3-3910",
                            Nama = "Cadangan Koperasi",
                            SaldoNormal = "Kredit",
                            Sistem = true,
                            Tipe = "Ekuitas"
                        },
                        new
                        {
                            Id = 21,
                            Aktif = true,
                            DibuatPada = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Kode = "5-5910",
                            Nama = "Beban Umum & Administrasi",
                            SaldoNormal = "Debit",
                            Sistem = false,
                            Tipe = "Beban"
                        },
                        new
                        {
                            Id = 22,
                            Aktif = true,
                            DibuatPada = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Kode = "5-5920",
                            Nama = "Beban Penyisihan Piutang Tak Tertagih",
                            SaldoNormal = "Debit",
                            Sistem = false,
                            Tipe = "Beban"
                        },
                        new
                        {
                            Id = 23,
                            Aktif = true,
                            DibuatPada = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Kode = "3-3990",
                            Nama = "Kliring Migrasi Data Lama",
                            SaldoNormal = "Kredit",
                            Sistem = true,
                            Tipe = "Ekuitas"
                        },
                        new
                        {
                            Id = 24,
                            Aktif = true,
                            DibuatPada = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Kode = "1-1500",
                            Nama = "Piutang Non-Anggota",
                            SaldoNormal = "Debit",
                            Sistem = false,
                            Tipe = "Aset"
                        },
                        new
                        {
                            Id = 25,
                            Aktif = true,
                            DibuatPada = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Kode = "1-1510",
                            Nama = "Cadangan Penyisihan Piutang Tak Tertagih",
                            SaldoNormal = "Debit",
                            Sistem = false,
                            Tipe = "Aset"
                        },
                        new
                        {
                            Id = 26,
                            Aktif = true,
                            DibuatPada = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Kode = "2-2700",
                            Nama = "Utang Non-Anggota",
                            SaldoNormal = "Kredit",
                            Sistem = false,
                            Tipe = "Liabilitas"
                        },
                        new
                        {
                            Id = 27,
                            Aktif = true,
                            DibuatPada = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Kode = "1-1250",
                            Nama = "Piutang Lain-lain",
                            SaldoNormal = "Debit",
                            Sistem = false,
                            Tipe = "Aset"
                        },
                        new
                        {
                            Id = 28,
                            Aktif = true,
                            DibuatPada = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Kode = "2-2650",
                            Nama = "Utang Lain-lain",
                            SaldoNormal = "Kredit",
                            Sistem = false,
                            Tipe = "Liabilitas"
                        },
                        new
                        {
                            Id = 29,
                            Aktif = true,
                            DibuatPada = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Kode = "2-2660",
                            Nama = "Biaya Yang Masih Harus Dibayar",
                            SaldoNormal = "Kredit",
                            Sistem = false,
                            Tipe = "Liabilitas"
                        },
                        new
                        {
                            Id = 30,
                            Aktif = true,
                            DibuatPada = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Kode = "5-5400",
                            Nama = "Beban Pokok Pinjaman (HPP)",
                            SaldoNormal = "Debit",
                            Sistem = false,
                            Tipe = "Beban"
                        },
                        new
                        {
                            Id = 31,
                            Aktif = true,
                            DibuatPada = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Kode = "5-5930",
                            Nama = "Beban di Luar Usaha",
                            SaldoNormal = "Debit",
                            Sistem = false,
                            Tipe = "Beban"
                        },
                        new
                        {
                            Id = 32,
                            Aktif = true,
                            DibuatPada = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Kode = "2-2450",
                            Nama = "Utang Pajak",
                            SaldoNormal = "Kredit",
                            Sistem = false,
                            Tipe = "Liabilitas"
                        });
                });

            modelBuilder.Entity("Anggota", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit");

                    b.Property<string>("Alamat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NamaLengkap")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NomorAnggota")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("NomorIdentitas")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NomorTelepon")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("TanggalBergabung")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("NomorAnggota")
                        .IsUnique();

                    b.ToTable("Anggota");
                });

            modelBuilder.Entity("AngsuranPinjaman", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AngsuranKe")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DibayarPada")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Jasa")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("JatuhTempo")
                        .HasColumnType("datetime2");

                    b.Property<string>("Jenis")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal?>("JumlahDibayar")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PinjamanId")
                        .HasColumnType("int");

                    b.Property<decimal>("Pokok")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("PinjamanId", "AngsuranKe");

                    b.ToTable("AngsuranPinjaman");

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("AngsuranTagihanKredit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AngsuranKe")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DibayarPada")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("JatuhTempo")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("JumlahDibayar")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Nominal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("TagihanKreditId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TagihanKreditId", "AngsuranKe");

                    b.ToTable("AngsuranTagihanKredit");
                });

            modelBuilder.Entity("AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aksi")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("AlamatIp")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Detail")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int?>("EntitasId")
                        .HasColumnType("int");

                    b.Property<string>("Modul")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int?>("PelakuId")
                        .HasColumnType("int");

                    b.Property<string>("PelakuNama")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PelakuPeran")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Ringkasan")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("WaktuUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Modul");

                    b.HasIndex("WaktuUtc");

                    b.ToTable("AuditLog");
                });

            modelBuilder.Entity("DbAuditLogEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AppName")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("DataSebelum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DataSesudah")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DbLogin")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("HostName")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("KunciPrimer")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Operasi")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("PrevHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Tabel")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<DateTime>("WaktuUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("DbAuditLog", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("EratAgenda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Deskripsi")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("DibuatPada")
                        .HasColumnType("datetime2");

                    b.Property<string>("Judul")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("MulaiPada")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("SelesaiPada")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("EratAgenda");
                });

            modelBuilder.Entity("EratOpsi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EratAgendaId")
                        .HasColumnType("int");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Urutan")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EratAgendaId");

                    b.ToTable("EratOpsi");
                });

            modelBuilder.Entity("EratSuara", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DipilihPada")
                        .HasColumnType("datetime2");

                    b.Property<int>("EratAgendaId")
                        .HasColumnType("int");

                    b.Property<int>("EratOpsiId")
                        .HasColumnType("int");

                    b.Property<int>("PenggunaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EratOpsiId");

                    b.HasIndex("PenggunaId");

                    b.HasIndex("EratAgendaId", "PenggunaId")
                        .IsUnique();

                    b.ToTable("EratSuara");
                });

            modelBuilder.Entity("JenisSimpanan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit");

                    b.Property<string>("Deskripsi")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Kode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Kode")
                        .IsUnique();

                    b.ToTable("JenisSimpanan");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Aktif = true,
                            Deskripsi = "Simpanan awal keanggotaan.",
                            Kode = "POKOK",
                            Nama = "Simpanan Pokok"
                        },
                        new
                        {
                            Id = 2,
                            Aktif = true,
                            Deskripsi = "Simpanan berkala anggota.",
                            Kode = "WAJIB",
                            Nama = "Simpanan Wajib"
                        },
                        new
                        {
                            Id = 3,
                            Aktif = true,
                            Deskripsi = "Simpanan tambahan sesuai kemampuan anggota.",
                            Kode = "SUKARELA",
                            Nama = "Simpanan Sukarela"
                        },
                        new
                        {
                            Id = 4,
                            Aktif = true,
                            Deskripsi = "Simpanan dengan jangka waktu tertentu.",
                            Kode = "BERJANGKA",
                            Nama = "Simpanan Berjangka"
                        });
                });

            modelBuilder.Entity("JurnalBaris", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AkunId")
                        .HasColumnType("int");

                    b.Property<decimal>("Debit")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("JurnalEntriId")
                        .HasColumnType("int");

                    b.Property<string>("Keterangan")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<decimal>("Kredit")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("AkunId");

                    b.HasIndex("JurnalEntriId");

                    b.ToTable("JurnalBaris");

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("JurnalEntri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DibuatPada")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DicatatOlehId")
                        .HasColumnType("int");

                    b.Property<string>("Keterangan")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("NomorJurnal")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("ReferensiId")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("ReferensiModul")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Sumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("Tanggal")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DicatatOlehId");

                    b.HasIndex("NomorJurnal")
                        .IsUnique();

                    b.HasIndex("Tanggal");

                    b.ToTable("JurnalEntri");

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("KonfigurasiKoperasi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BungaDepositoTahunan")
                        .HasPrecision(5, 4)
                        .HasColumnType("decimal(5,4)");

                    b.Property<decimal>("BungaSukarelaTahunan")
                        .HasPrecision(5, 4)
                        .HasColumnType("decimal(5,4)");

                    b.Property<string>("CatatanNeraca")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DiperbaruiPada")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("SimpananPokokNominal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SimpananWajibNominal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TanggalTagihWajib")
                        .HasColumnType("int");

                    b.Property<decimal>("TarifPph")
                        .HasPrecision(5, 4)
                        .HasColumnType("decimal(5,4)");

                    b.Property<decimal>("TarifPphShu")
                        .HasPrecision(5, 4)
                        .HasColumnType("decimal(5,4)");

                    b.HasKey("Id");

                    b.ToTable("KonfigurasiKoperasi");

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BungaDepositoTahunan = 0.045m,
                            BungaSukarelaTahunan = 0.025m,
                            DiperbaruiPada = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SimpananPokokNominal = 100000m,
                            SimpananWajibNominal = 50000m,
                            TanggalTagihWajib = 25,
                            TarifPph = 0.20m,
                            TarifPphShu = 0.15m
                        });
                });

            modelBuilder.Entity("LaporanTahunan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit");

                    b.Property<string>("Deskripsi")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("DiterbitkanPada")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Judul")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Tahun")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Tahun");

                    b.ToTable("LaporanTahunan");
                });

            modelBuilder.Entity("MutasiSimpanan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Jenis")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Keterangan")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<decimal>("Nominal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SaldoSetelah")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SimpananId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TanggalTransaksi")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SimpananId");

                    b.ToTable("MutasiSimpanan");

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("PembayaranPinjaman", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AngsuranKe")
                        .HasColumnType("int");

                    b.Property<string>("BuktiTransferUrl")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Catatan")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("CatatanReview")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("DiajukanPada")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DiputuskanPada")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("JasaDibebaskan")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Jenis")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("JumlahDiajukan")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PenggunaId")
                        .HasColumnType("int");

                    b.Property<int>("PinjamanId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("PenggunaId");

                    b.HasIndex("PinjamanId", "Status");

                    b.ToTable("PembayaranPinjaman");
                });

            modelBuilder.Entity("PembelianProduk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Catatan")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("CatatanReview")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("DiajukanPada")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DiprosesPada")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("HargaSatuan")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Jenis")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal>("Jumlah")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<string>("MetodePembayaran")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("NomorTransaksi")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("PembeliId")
                        .HasColumnType("int");

                    b.Property<int>("ProdukId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("NomorTransaksi")
                        .IsUnique();

                    b.HasIndex("PembeliId");

                    b.HasIndex("ProdukId");

                    b.ToTable("PembelianProduk");
                });

            modelBuilder.Entity("PengajuanPinjaman", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BungaTahunan")
                        .HasPrecision(5, 4)
                        .HasColumnType("decimal(5,4)");

                    b.Property<string>("CatatanReview")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("DibuatPada")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DiputuskanPada")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("EstimasiCicilanBulanan")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("EstimasiTotalJasa")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Nominal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NomorPengajuan")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("PenggunaId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("SuratRekomendasiUrl")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("TenorBulan")
                        .HasColumnType("int");

                    b.Property<string>("Tujuan")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("NomorPengajuan")
                        .IsUnique();

                    b.HasIndex("PenggunaId");

                    b.ToTable("PengajuanPinjaman");
                });

            modelBuilder.Entity("Pengguna", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit");

                    b.Property<string>("Alamat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DibuatPada")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DisetujuiPada")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FotoUrl")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("NamaLengkap")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NomorIndukKaryawan")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("NomorTelepon")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Peran")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("Anggota");

                    b.Property<int>("PercobaanLoginGagal")
                        .HasColumnType("int");

                    b.Property<string>("StatusKeanggotaan")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("Aktif");

                    b.Property<DateTime?>("TerkunciSampai")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("NomorIndukKaryawan")
                        .IsUnique();

                    b.ToTable("Pengguna");

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("Pinjaman", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AngsuranPerBulan")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("AngsuranTerbayar")
                        .HasColumnType("int");

                    b.Property<decimal>("BungaTahunan")
                        .HasPrecision(5, 4)
                        .HasColumnType("decimal(5,4)");

                    b.Property<DateTime>("DibuatPada")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("JasaPerBulan")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("LunasPada")
                        .HasColumnType("datetime2");

                    b.Property<string>("NomorPinjaman")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("PengajuanPinjamanId")
                        .HasColumnType("int");

                    b.Property<int>("PenggunaId")
                        .HasColumnType("int");

                    b.Property<decimal>("Pokok")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PokokPerBulan")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SisaPokok")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("TanggalMulai")
                        .HasColumnType("datetime2");

                    b.Property<int>("TenorBulan")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NomorPinjaman")
                        .IsUnique();

                    b.HasIndex("PengajuanPinjamanId")
                        .IsUnique();

                    b.HasIndex("PenggunaId");

                    b.ToTable("Pinjaman");

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("PostingBungaSukarela", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BungaBruto")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BungaNeto")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DiposkanPada")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Nominal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Pajak")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PenggunaId")
                        .HasColumnType("int");

                    b.Property<string>("Periode")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.HasKey("Id");

                    b.HasIndex("PenggunaId", "Periode")
                        .IsUnique();

                    b.ToTable("PostingBungaSukarela");
                });

            modelBuilder.Entity("Produk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit");

                    b.Property<string>("CatatanReview")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Deskripsi")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("DiajukanOlehId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DiperbaruiPada")
                        .HasColumnType("datetime2");

                    b.Property<string>("FotoUrl")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<decimal>("Harga")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Jenis")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Kode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Satuan")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal>("Stok")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<string>("Sumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("DiajukanOlehId");

                    b.HasIndex("Kode")
                        .IsUnique();

                    b.ToTable("Produk");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Aktif = true,
                            DiperbaruiPada = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Harga = 78000m,
                            Jenis = "Jual",
                            Kode = "PRD-BRSPRM5",
                            Nama = "Beras Premium 5 kg",
                            Satuan = "paket",
                            Status = "Disetujui",
                            Stok = 0m,
                            Sumber = "Koperasi"
                        },
                        new
                        {
                            Id = 2,
                            Aktif = true,
                            DiperbaruiPada = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Harga = 36500m,
                            Jenis = "Jual",
                            Kode = "PRD-MNYK2",
                            Nama = "Minyak Goreng 2 L",
                            Satuan = "botol",
                            Status = "Disetujui",
                            Stok = 0m,
                            Sumber = "Koperasi"
                        },
                        new
                        {
                            Id = 3,
                            Aktif = true,
                            DiperbaruiPada = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Harga = 17000m,
                            Jenis = "Jual",
                            Kode = "PRD-GULA1",
                            Nama = "Gula Pasir 1 kg",
                            Satuan = "paket",
                            Status = "Disetujui",
                            Stok = 0m,
                            Sumber = "Koperasi"
                        },
                        new
                        {
                            Id = 4,
                            Aktif = false,
                            DiperbaruiPada = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Harga = 0m,
                            Jenis = "Jual",
                            Kode = "PRD-MIGRASI",
                            Nama = "Migrasi Data Lama",
                            Satuan = "paket",
                            Status = "Disetujui",
                            Stok = 0m,
                            Sumber = "Koperasi"
                        });
                });

            modelBuilder.Entity("ProdukBerjangka", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DibuatPada")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("Nominal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TenorBulan")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ProdukBerjangka");
                });

            modelBuilder.Entity("ProfilKoperasi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AlamatKantor")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("DiperbaruiPada")
                        .HasColumnType("datetime2");

                    b.Property<string>("Misi")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("NomorAktaPendirian")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("TanggalAkta")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TanggalDidirikan")
                        .HasColumnType("datetime2");

                    b.Property<string>("Visi")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.ToTable("ProfilKoperasi");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AlamatKantor = "JL KIG RAYA SELATAN A-5, GRESIK 61121",
                            DiperbaruiPada = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Misi = "A. Melaksanakan amanat AD/ART untuk melayani Anggota sebagai prioritas utama.\nB. Mengembangkan unit usaha yang sudah berjalan dan mengembangkan usaha baru.\nC. Bekerjasama dengan mitra usaha dan atau Lembaga Keuangan untuk memperkuat permodalan.\nD. Bersama dengan pihak-pihak berkepentingan mewujudkan kesejahteraan Anggota.",
                            NomorAktaPendirian = "160/BN/XVI.6/VI/2010",
                            TanggalAkta = new DateTime(2010, 6, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TanggalDidirikan = new DateTime(2009, 7, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Visi = "Mendorong ekspansi usaha koperasi sehingga menjadi koperasi yang mandiri dan tangguh berlandaskan amanah dalam membangun ekonomi bersama dan berkeadilan demi kesejahteraan Anggota."
                        });
                });

            modelBuilder.Entity("RatTahunan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CatatanTambahan")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("DiperbaruiPada")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Dipublikasikan")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DipublikasikanPada")
                        .HasColumnType("datetime2");

                    b.Property<string>("KegiatanBisnis")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("KegiatanSosial")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<decimal?>("RabBebanOperasional")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("RabBebanUmum")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("RabCadanganPiutang")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("RabPendapatanLain")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("RabPendapatanPinjaman")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("RealisasiPajakShu")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RencanaBisnisTahunDepan")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("RencanaSosialTahunDepan")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int>("Tahun")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Tahun")
                        .IsUnique();

                    b.ToTable("RatTahunan");
                });

            modelBuilder.Entity("ShuAnggota", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BelanjaAnggota")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("JasaPinjamanAnggota")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Jma")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Jua")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Pajak")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PenggunaId")
                        .HasColumnType("int");

                    b.Property<int>("ShuRunId")
                        .HasColumnType("int");

                    b.Property<decimal>("SimpananAnggota")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalShu")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalShuNeto")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TransaksiAnggota")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("PenggunaId");

                    b.HasIndex("ShuRunId", "PenggunaId")
                        .IsUnique();

                    b.ToTable("ShuAnggota");

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("ShuRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CadanganAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("DifinalisasiOlehId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DifinalisasiPada")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("JasaPengurusPool")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PersenAnggota")
                        .HasPrecision(5, 4)
                        .HasColumnType("decimal(5,4)");

                    b.Property<decimal>("PersenCadangan")
                        .HasPrecision(5, 4)
                        .HasColumnType("decimal(5,4)");

                    b.Property<decimal>("PersenJasaModal")
                        .HasPrecision(5, 4)
                        .HasColumnType("decimal(5,4)");

                    b.Property<decimal>("PersenJasaUsaha")
                        .HasPrecision(5, 4)
                        .HasColumnType("decimal(5,4)");

                    b.Property<decimal>("PersenPengurus")
                        .HasPrecision(5, 4)
                        .HasColumnType("decimal(5,4)");

                    b.Property<int>("Tahun")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPajak")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalShu")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalShuNeto")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalSimpananSemuaAnggota")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalTransaksiSemuaAnggota")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("DifinalisasiOlehId");

                    b.HasIndex("Tahun")
                        .IsUnique();

                    b.ToTable("ShuRun");

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("Simpanan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit");

                    b.Property<int>("JenisSimpananId")
                        .HasColumnType("int");

                    b.Property<string>("NomorRekening")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("PenggunaId")
                        .HasColumnType("int");

                    b.Property<decimal>("Saldo")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("TanggalBuka")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("JenisSimpananId");

                    b.HasIndex("NomorRekening")
                        .IsUnique();

                    b.HasIndex("PenggunaId");

                    b.ToTable("Simpanan");

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("SimpananBerjangka", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AlasanPencairan")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("BuktiTransferUrl")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<decimal?>("BungaDibayar")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("BungaNeto")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CatatanReview")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("DiajukanPada")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DicairkanPada")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Nominal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NomorSertifikat")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<decimal?>("PajakBunga")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("PencairanDiajukan")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("PencairanDiajukanPada")
                        .HasColumnType("datetime2");

                    b.Property<int>("PenggunaId")
                        .HasColumnType("int");

                    b.Property<int>("ProdukBerjangkaId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("TanggalJatuhTempo")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TanggalMulai")
                        .HasColumnType("datetime2");

                    b.Property<int>("TenorBulan")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NomorSertifikat")
                        .IsUnique();

                    b.HasIndex("PenggunaId");

                    b.HasIndex("ProdukBerjangkaId");

                    b.ToTable("SimpananBerjangka");

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("SukarelaRutin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CatatanReview")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("DiajukanPada")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DiputuskanPada")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Nominal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PenggunaId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("TanggalSetor")
                        .HasColumnType("int");

                    b.Property<string>("TerakhirDijalankanPeriode")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.HasKey("Id");

                    b.HasIndex("PenggunaId", "Status");

                    b.ToTable("SukarelaRutin");
                });

            modelBuilder.Entity("TagihanKredit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("AngsuranPerBulan")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DibuatPada")
                        .HasColumnType("datetime2");

                    b.Property<string>("Keterangan")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("LunasPada")
                        .HasColumnType("datetime2");

                    b.Property<int>("PembelianProdukId")
                        .HasColumnType("int");

                    b.Property<int>("PenggunaId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("TenorBulan")
                        .HasColumnType("int");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("PembelianProdukId")
                        .IsUnique();

                    b.HasIndex("PenggunaId");

                    b.ToTable("TagihanKredit");
                });

            modelBuilder.Entity("TagihanWajib", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CatatanReview")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("DibuatPada")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DiprosesPada")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("JatuhTempo")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Nominal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PenggunaId")
                        .HasColumnType("int");

                    b.Property<string>("Periode")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("PenggunaId", "Periode")
                        .IsUnique();

                    b.ToTable("TagihanWajib");
                });

            modelBuilder.Entity("TransaksiSukarela", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BuktiTransferUrl")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Catatan")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("CatatanReview")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("DiajukanPada")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DiprosesPada")
                        .HasColumnType("datetime2");

                    b.Property<string>("Jenis")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("Nominal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PenggunaId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("PenggunaId", "Status");

                    b.ToTable("TransaksiSukarela");
                });

            modelBuilder.Entity("AngsuranPinjaman", b =>
                {
                    b.HasOne("Pinjaman", "Pinjaman")
                        .WithMany("Angsuran")
                        .HasForeignKey("PinjamanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pinjaman");
                });

            modelBuilder.Entity("AngsuranTagihanKredit", b =>
                {
                    b.HasOne("TagihanKredit", "TagihanKredit")
                        .WithMany("Angsuran")
                        .HasForeignKey("TagihanKreditId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TagihanKredit");
                });

            modelBuilder.Entity("EratOpsi", b =>
                {
                    b.HasOne("EratAgenda", "EratAgenda")
                        .WithMany("Opsi")
                        .HasForeignKey("EratAgendaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EratAgenda");
                });

            modelBuilder.Entity("EratSuara", b =>
                {
                    b.HasOne("EratAgenda", "EratAgenda")
                        .WithMany("Suara")
                        .HasForeignKey("EratAgendaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("EratOpsi", "EratOpsi")
                        .WithMany("Suara")
                        .HasForeignKey("EratOpsiId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Pengguna", "Pengguna")
                        .WithMany()
                        .HasForeignKey("PenggunaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EratAgenda");

                    b.Navigation("EratOpsi");

                    b.Navigation("Pengguna");
                });

            modelBuilder.Entity("JurnalBaris", b =>
                {
                    b.HasOne("AkunAkuntansi", "Akun")
                        .WithMany("Baris")
                        .HasForeignKey("AkunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JurnalEntri", "JurnalEntri")
                        .WithMany("Baris")
                        .HasForeignKey("JurnalEntriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Akun");

                    b.Navigation("JurnalEntri");
                });

            modelBuilder.Entity("JurnalEntri", b =>
                {
                    b.HasOne("Pengguna", "DicatatOleh")
                        .WithMany()
                        .HasForeignKey("DicatatOlehId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DicatatOleh");
                });

            modelBuilder.Entity("MutasiSimpanan", b =>
                {
                    b.HasOne("Simpanan", "Simpanan")
                        .WithMany("Mutasi")
                        .HasForeignKey("SimpananId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Simpanan");
                });

            modelBuilder.Entity("PembayaranPinjaman", b =>
                {
                    b.HasOne("Pengguna", "Pengguna")
                        .WithMany()
                        .HasForeignKey("PenggunaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Pinjaman", "Pinjaman")
                        .WithMany()
                        .HasForeignKey("PinjamanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pengguna");

                    b.Navigation("Pinjaman");
                });

            modelBuilder.Entity("PembelianProduk", b =>
                {
                    b.HasOne("Pengguna", "Pembeli")
                        .WithMany()
                        .HasForeignKey("PembeliId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Produk", "Produk")
                        .WithMany()
                        .HasForeignKey("ProdukId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pembeli");

                    b.Navigation("Produk");
                });

            modelBuilder.Entity("PengajuanPinjaman", b =>
                {
                    b.HasOne("Pengguna", "Pengguna")
                        .WithMany()
                        .HasForeignKey("PenggunaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pengguna");
                });

            modelBuilder.Entity("Pinjaman", b =>
                {
                    b.HasOne("PengajuanPinjaman", "Pengajuan")
                        .WithOne("Pinjaman")
                        .HasForeignKey("Pinjaman", "PengajuanPinjamanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Pengguna", "Pengguna")
                        .WithMany()
                        .HasForeignKey("PenggunaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pengajuan");

                    b.Navigation("Pengguna");
                });

            modelBuilder.Entity("PostingBungaSukarela", b =>
                {
                    b.HasOne("Pengguna", "Pengguna")
                        .WithMany()
                        .HasForeignKey("PenggunaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pengguna");
                });

            modelBuilder.Entity("Produk", b =>
                {
                    b.HasOne("Pengguna", "DiajukanOleh")
                        .WithMany()
                        .HasForeignKey("DiajukanOlehId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DiajukanOleh");
                });

            modelBuilder.Entity("ShuAnggota", b =>
                {
                    b.HasOne("Pengguna", "Pengguna")
                        .WithMany()
                        .HasForeignKey("PenggunaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ShuRun", "ShuRun")
                        .WithMany("Rincian")
                        .HasForeignKey("ShuRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pengguna");

                    b.Navigation("ShuRun");
                });

            modelBuilder.Entity("ShuRun", b =>
                {
                    b.HasOne("Pengguna", "DifinalisasiOleh")
                        .WithMany()
                        .HasForeignKey("DifinalisasiOlehId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DifinalisasiOleh");
                });

            modelBuilder.Entity("Simpanan", b =>
                {
                    b.HasOne("JenisSimpanan", "JenisSimpanan")
                        .WithMany("Simpanan")
                        .HasForeignKey("JenisSimpananId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Pengguna", "Pengguna")
                        .WithMany()
                        .HasForeignKey("PenggunaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("JenisSimpanan");

                    b.Navigation("Pengguna");
                });

            modelBuilder.Entity("SimpananBerjangka", b =>
                {
                    b.HasOne("Pengguna", "Pengguna")
                        .WithMany()
                        .HasForeignKey("PenggunaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProdukBerjangka", "Produk")
                        .WithMany("SimpananBerjangka")
                        .HasForeignKey("ProdukBerjangkaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pengguna");

                    b.Navigation("Produk");
                });

            modelBuilder.Entity("SukarelaRutin", b =>
                {
                    b.HasOne("Pengguna", "Pengguna")
                        .WithMany()
                        .HasForeignKey("PenggunaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pengguna");
                });

            modelBuilder.Entity("TagihanKredit", b =>
                {
                    b.HasOne("PembelianProduk", "Pembelian")
                        .WithOne("TagihanKredit")
                        .HasForeignKey("TagihanKredit", "PembelianProdukId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pengguna", "Pengguna")
                        .WithMany()
                        .HasForeignKey("PenggunaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pembelian");

                    b.Navigation("Pengguna");
                });

            modelBuilder.Entity("TagihanWajib", b =>
                {
                    b.HasOne("Pengguna", "Pengguna")
                        .WithMany()
                        .HasForeignKey("PenggunaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pengguna");
                });

            modelBuilder.Entity("TransaksiSukarela", b =>
                {
                    b.HasOne("Pengguna", "Pengguna")
                        .WithMany()
                        .HasForeignKey("PenggunaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pengguna");
                });

            modelBuilder.Entity("AkunAkuntansi", b =>
                {
                    b.Navigation("Baris");
                });

            modelBuilder.Entity("EratAgenda", b =>
                {
                    b.Navigation("Opsi");

                    b.Navigation("Suara");
                });

            modelBuilder.Entity("EratOpsi", b =>
                {
                    b.Navigation("Suara");
                });

            modelBuilder.Entity("JenisSimpanan", b =>
                {
                    b.Navigation("Simpanan");
                });

            modelBuilder.Entity("JurnalEntri", b =>
                {
                    b.Navigation("Baris");
                });

            modelBuilder.Entity("PembelianProduk", b =>
                {
                    b.Navigation("TagihanKredit");
                });

            modelBuilder.Entity("PengajuanPinjaman", b =>
                {
                    b.Navigation("Pinjaman");
                });

            modelBuilder.Entity("Pinjaman", b =>
                {
                    b.Navigation("Angsuran");
                });

            modelBuilder.Entity("ProdukBerjangka", b =>
                {
                    b.Navigation("SimpananBerjangka");
                });

            modelBuilder.Entity("ShuRun", b =>
                {
                    b.Navigation("Rincian");
                });

            modelBuilder.Entity("Simpanan", b =>
                {
                    b.Navigation("Mutasi");
                });

            modelBuilder.Entity("TagihanKredit", b =>
                {
                    b.Navigation("Angsuran");
                });
#pragma warning restore 612, 618
        }
    }
}
